### ISSUE TITLE
syncing mailbot code not exist error

### ISSUE THREAD

**Issue by soyapark** [soyapark/murmur#62] opened 2019-03-08 18:57 UTC
```
[2019-03-08 12:56:04,856: ERROR/Worker-2] User inbox syncing fails sbhappylee@gmail.com. Stop syncing 'NoneType' object has no attribute 'code'
Traceback (most recent call last):
  File "/home/ubuntu/production/mailx/http_handler/tasks.py", line 195, in init_sync_user_inbox
    mailbox._run_user_code()
  File "/home/ubuntu/production/mailx/browser/models/mailbox.py", line 75, in _run_user_code
    code = self._imap_account.current_mode.code
AttributeError: 'NoneType' object has no attribute 'code'
```

**Comment by lukesmurray** [comment] 2019-03-08 19:10
I think this is fixed on master. 

https://github.com/soyapark/murmur/blob/49669f6fc6763edb4ce034c962b29635d81b040b/browser/models/mailbox.py#L90-L93

Can you double check that the issue is still being raised. The trick is to check if the current_mode is not None

**Comment by lukesmurray** [comment] 2019-03-08 19:12
This is also how I found #60

**Comment by lukesmurray** [comment] 2019-03-08 20:09
I believe this is

**Closed by lukesmurray** 2019-03-08 20:09 UTC
Labels: bug
